# bin/bash
clear
echo ""
echo "                 ██████╗ ██╗     ███╗   ██╗ ██╗██████╗ ██████╗  ██╗"
echo "                 ╚════██╗██║     ████╗  ██║███║██╔══██╗██╔══██╗███║"
echo "                  █████╔╝██║     ██╔██╗ ██║╚██║██████╔╝██████╔╝╚██║"
echo "                  ╚═══██╗██║     ██║╚██╗██║ ██║██╔═══╝ ██╔══██╗ ██║"
echo "                 ██████╔╝███████╗██║ ╚████║ ██║██║     ██║  ██║ ██║"
echo "                 ╚═════╝ ╚══════╝╚═╝  ╚═══╝ ╚═╝╚═╝     ╚═╝  ╚═╝ ╚═╝"
echo "                               -----------------------             "
echo "                                  3ln1pr1@keemail.me"
echo " ____________  ____________   ____________  ____________  ____________  ____________"
echo "/___________/\/___________/\ /___________/\/___________/\/___________/\/___________/\ "
echo "\___________\/\___________\/ \___________\/\___________\/\___________\/\____2019___\/ "
echo "                                                                                 "
echo "                                    ''..--..''                                   "
echo "                             '-+oyhddddddddmmmmhys+-'                            "
echo "                          .+yddhhhhhhhhhhhhhhhhddddddh+.                         "
echo "      osoos+.           -ydhhhhhhhhhhhhhhhhhhhhhhhhhhhdmo'           .+sooso     "
echo "     +s    .ss         +mhdddddddhhhhhhhhhhhhhhhhhhhhhhhdh.         ss.    s+    "
echo "     +hs'    -y:      omddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdd.      :y-    'sh+    "
echo "     s+'s    .:+o'   sdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddd'   'o+-.    s'+s    "
echo "    -d .-     -+h+.mhhhhhhhhhhhddddhhdddddddhhhhhhhhhhhhdmho:+h+-     -.  d-   "
echo "    s+   -       .+dhmhhhhhdddddhhhhhhhhhhhddmmmmmdddhhhhhddmhdm.       -   +s   "
echo "    :y:://os+:.     -ddhddo+-'                 ''.-:+smdhhhmdhhd:  -/oyo//::y:   "
echo "     ':/:::/ooo+-''' -mm+ ':. '...'..'         ''... .-/ddhmdhhd:/osoo/:::/:'    "
echo "               -/os+. .d/ -+'/syyyhhhd:    +yhhhyyso: +:.dmmhdmdd+-              "
echo "                   ./ooyy-+ hmmmmmmmmmy   'mmmmmmmmmm+ +/mmmmmddhd/              "
echo "                       .ds' smmmmmmmmh.    +mmmmmmmmm- 'mmddhmhdhhdy'            "
echo "                        yd   +ydmmdy:   --  '+hmmmmh:   dmdhhmdhhhhdh'           "
echo "                        h:             +mm-       '     :mdhhdmdhdhhds           "
echo "                        h'            /mmmd-           .-mddhhmmhhdhhm.          "
echo "                        .oo++oy/:-.'  dmsdm+  '.-:+hs++ss/mdhdsodhhdhd/          "
echo "                       ':++:yosd-     ''  '      :dydh:++:ymhd/ ydhhdd+          "
echo "                    -+o+.   /o dd'   '          .mm'd/   .+hdd: 'hdhhdh          "
echo "      -/++++////+oso:'     .-s'omy-/-/-:--/--:--hms d-.    'hmysoomdhhms++/-     "
echo "    's:'    ''+y+-      .-oyhy.-mm+::/--.---/:/+mm..dhs+-.  'y- -+ysydhd+'':s'   "
echo "    o.-      '       .:+yds- s -+soo++:o//o:+++os:'.y -sds+/.       ':/ohs' 'o   "
echo "    -s+:'         .+oshh/'   o.  '  -.-+:::-:.'  ---o   '/hhso+.         '-/s-   "
echo "      .+yh/-.'   -o:dy-      's-       '   '  ''. -o'      -yh:o-   '.-:hy+.     "
echo "         :y  '  '/'ds          -///+/-..   ':o++/:.          sh'/'  '  y:        "
echo "          y-      oh                ':+++///-'                ho      -y         "
echo "          .ys++++yy'                                          'yy++++sy.         "
echo "            '....'                                              '....'           "
echo "                                                                                 "
echo " "
echo ""
echo "                                                                                 "
echo " "
echo ""
echo "                                                                                 "
echo " "
echo ""

