#!/bin/bash
#titulo         :descarga.sh
#descripcion    :Este Script se usa para descargar archivos del servidor de forma facil y actualizando los archivos si ya existen.
#autor	        :Elias Nieva Prieto
#fecha          :2019-05-27
#version        :0.4
#uso		    :bash ./descarga.sh
#notas          :Install Nano and Emacs para usar el Script
#bash_version   :4.1.5(1)-version
#e-mail         :informatica@ctbell.com
#Empresa        :C.T.Bell s.l.u
#Telefono       :966 812 131
#===3=====l======N=======1=========P=======r========1======@===3=====l======N=======1=========P=======r========1======@
#============================================================================
#                           INICIAMOS EL SCRIPT                             #
#============================================================================

# Variables Genericas cargadas desde el Script "Variables.sh"
VARIABLE=~/scripts/variables.sh
source $VARIABLE

#============================================================================
#                      DEFINICION DE VARIABLES PROPIAS                      #
#============================================================================
FECHA=`date +%Y-%m-%d`
HORA=`date +%H:%M`
USERID=`id -g`
IP=`hostname -I  | cut -d " " -f1`
IP2=`hostname -I  | cut -d " " -f2`
FOLDER=$1
ARCHIVO=$2

#============================================================================
#                       INICIO DEL MENÚ DE OPCIONES                         #
#============================================================================
clear
    if [ "x$FOLDER" = "x" ]; then

        echo -e "${Blanco}RECUERDA: La proxima vez puedes usar la sistaxis \n\`bash${nc} ./descarga ${Cyanclaro}NOMBRE_CARPETA ${Amarillo}NOMBRE_ARCHIVO ${nc}\` "
        echo -e "============================================================================ ${nc}"
        echo "La Carpeta por Defecto de los SCRIPTS es $FOLDER1"
        echo -e "Introduce la ${Blanco}Carpeta${nc} donde los quieres Descargar${Azulclaro}"
        read FOLDER
    else
        echo OK
    fi
clear
        echo ""
        echo -e "${nc}La Carpeta Introducida es:${Blanco} $FOLDER ${nc}"
        echo -e "============================================================================ ${nc}"
        echo ""
    if [ "x$ARCHIVO" = "x" ]; then
        echo -e "${Blanco}RECUERDA: La proxima vez puedes usar la sistaxis \n\`bash${nc} ./descarga ${Cyanclaro}NOMBRE_CARPETA ${Amarillo}NOMBRE_ARCHIVO ${nc}\` "
        echo -e "============================================================================ ${nc}"
        echo -e "Introduce el nombre del ${Blanco}Archivo${nc} a Descagar del Servidor${Azulclaro}"
        read ARCHIVO
    else
        echo -e "${Rojoclaro}OK"
    fi

clear
echo -e "${Amarillo}============================================================================"
echo "                 DESCARGA DE FICHEROS DESDE EL SERVIDOR                     "
echo -e "============================================================================ ${nc}"
echo ""
echo -e "${Rojoclaro}SEGURO QUE QUIERE DESCARGAR:\n${Azulclaro}$ARCHIVO \n${Rojoclaro}En la CARPETA: \n${Azulclaro}$FOLDER${nc}"
read -r -p "¿SEGURO QUE QUIERE DESCARGA? [Si/No] " input

            case $input in
            [sS][iI]|[sS])
             echo "SI"
                echo -e "${Blanco} Descarga en la carpeta $FOLDER${nc}"
         ;;
            [nN][oO]|[nN])
            clear
                echo -e "${Blanco}LE HAS DADO A CANCELAR${nc}"
                echo -e "${Azulclaro} VUELVA A EJECUTAR ${Rojoclaro}'bash ./descarga' ${Azulclaro}he introduzca los datos correctos${nc}"
                echo -e "${Blanco}Los Datos intrucidos antes eran:\n${nc}$ARCHIVO ${Rojoclaro}En la CARPETA ${Azulclaro}:$FOLDER${nc} "
                echo -e "============================================================================ ${nc}"
                echo -e "${Blanco}RECUERDA: Puedes usar la sistaxis \n\`${nc}bash ./descarga ${Cyanclaro}$FOLDER ${Amarillo}$ARCHIVO ${nc}\` \nPara Descargar mas rapido."
                echo -e "============================================================================ ${nc}"
            exit
         ;;
              *)
                 echo "Invalid input..."
         exit 1
         ;;
        esac

#echo "$URL, $ARCHIVO, $FOLDER "
    if [ -d $FOLDER ];then
        wget -P $FOLDER -N http://$URL$ARCHIVO
    else
        echo -e "${Rojoclaro} NO EXISTE $FOLDER ${nc}"
        read -r -p "Desea Crearlo? [Si/No] " input

            case $input in
            [sS][iI]|[sS])
             echo "SI"
                echo -e "${Blanco}Creo directorio $FOLDER${nc}"
                mkdir $FOLDER
                wget -P $FOLDER -N http://$URL$ARCHIVO
         ;;
            [nN][oO]|[nN])
            echo "NO"
            exit
         ;;
              *)
                 echo "Invalid input..."
         exit 1
         ;;
        esac

    fi
echo ""
sleep 2
ls -la $FOLDER
